version: '3'
services:
  flyway:
    image: flyway/flyway:7.1.1
    command: -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=P@ssw0rd -connectRetries=60 migrate
    volumes:
      - "${MIGRATION_ABS_PATH}:/flyway/sql"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=postgres
      - PGDATA=/data/postgres
    volumes:
      - ./scripts:/tmp
    ports:
      - 5432:5432
