SELECT 
    COLUMN_NAME, 
    DATA_TYPE, 
    IS_NULLABLE,
    TABLE_SCHEMA,
    TABLE_CATALOG,
    IS_IDENTITY,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    NUMERIC_PRECISION_RADIX 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA='$SCHEMA_NAME' AND TABLE_NAME='$TABLE_NAME';
